export const users = [
  {
    id: 1,
    name: 'Admin',
    email: 'admin@example.com',
    role: 'admin',
    active: true,
    password: 'admin123',
  },
  {
    id: 2,
    name: 'Admin1',
    email: 'admin1@example.com',
    role: 'admin',
    active: false,
    password: 'admin124',
  },
  {
    id: 3,
    name: 'Admin2',
    email: 'admin2@example.com',
    role: 'admin',
    active: true,
    password: 'admin125',
  },
  {
    id: 4,
    name: 'Buyer',
    email: 'buyer@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer123',
  },
  {
    id: 5,
    name: 'Buyer1',
    email: 'buyer1@example.com',
    role: 'buyer',
    active: false,
    password: 'buyer124',
  },
  {
    id: 6,
    name: 'Buyer2',
    email: 'buyer2@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer125',
  },
  {
    id: 7,
    name: 'User',
    email: 'user@example.com',
    role: 'user',
    active: false,
    password: 'user123',
  },
  {
    id: 8,
    name: 'User1',
    email: 'user1@example.com',
    role: 'user',
    active: true,
    password: 'user124',
  },
  {
    id: 9,
    name: 'User2',
    email: 'user2@example.com',
    role: 'user',
    active: true,
    password: 'user125',
  },
  {
    id: 10,
    name: 'Admin10',
    email: 'admin10@example.com',
    role: 'admin',
    active: true,
    password: 'admin10123',
  },
  {
    id: 11,
    name: 'Admin11',
    email: 'admin11@example.com',
    role: 'admin',
    active: false,
    password: 'admin11123',
  },
  {
    id: 12,
    name: 'Admin12',
    email: 'admin12@example.com',
    role: 'admin',
    active: true,
    password: 'admin12123',
  },
  {
    id: 13,
    name: 'Admin13',
    email: 'admin13@example.com',
    role: 'admin',
    active: false,
    password: 'admin13123',
  },
  {
    id: 14,
    name: 'Admin14',
    email: 'admin14@example.com',
    role: 'admin',
    active: true,
    password: 'admin14123',
  },
  {
    id: 15,
    name: 'Admin15',
    email: 'admin15@example.com',
    role: 'admin',
    active: false,
    password: 'admin15123',
  },
  {
    id: 16,
    name: 'Admin16',
    email: 'admin16@example.com',
    role: 'admin',
    active: true,
    password: 'admin16123',
  },
  {
    id: 17,
    name: 'Admin17',
    email: 'admin17@example.com',
    role: 'admin',
    active: false,
    password: 'admin17123',
  },
  {
    id: 18,
    name: 'Admin18',
    email: 'admin18@example.com',
    role: 'admin',
    active: true,
    password: 'admin18123',
  },
  {
    id: 19,
    name: 'Admin19',
    email: 'admin19@example.com',
    role: 'admin',
    active: false,
    password: 'admin19123',
  },
  {
    id: 20,
    name: 'Admin20',
    email: 'admin20@example.com',
    role: 'admin',
    active: true,
    password: 'admin20123',
  },
  {
    id: 21,
    name: 'Buyer21',
    email: 'buyer21@example.com',
    role: 'buyer',
    active: false,
    password: 'buyer21123',
  },
  {
    id: 22,
    name: 'Buyer22',
    email: 'buyer22@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer22123',
  },
  {
    id: 23,
    name: 'Buyer23',
    email: 'buyer23@example.com',
    role: 'buyer',
    active: false,
    password: 'buyer23123',
  },
  {
    id: 24,
    name: 'Buyer24',
    email: 'buyer24@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer24123',
  },
  {
    id: 25,
    name: 'Buyer25',
    email: 'buyer25@example.com',
    role: 'buyer',
    active: false,
    password: 'buyer25123',
  },
  {
    id: 26,
    name: 'Buyer26',
    email: 'buyer26@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer26123',
  },
  {
    id: 27,
    name: 'Buyer27',
    email: 'buyer27@example.com',
    role: 'buyer',
    active: false,
    password: 'buyer27123',
  },
  {
    id: 28,
    name: 'Buyer28',
    email: 'buyer28@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer28123',
  },
  {
    id: 29,
    name: 'Buyer29',
    email: 'buyer29@example.com',
    role: 'buyer',
    active: false,
    password: 'buyer29123',
  },
  {
    id: 30,
    name: 'Buyer30',
    email: 'buyer30@example.com',
    role: 'buyer',
    active: true,
    password: 'buyer30123',
  },
  {
    id: 31,
    name: 'User31',
    email: 'user31@example.com',
    role: 'user',
    active: false,
    password: 'user31123',
  },
  {
    id: 32,
    name: 'User32',
    email: 'user32@example.com',
    role: 'user',
    active: true,
    password: 'user32123',
  },
  {
    id: 33,
    name: 'User33',
    email: 'user33@example.com',
    role: 'user',
    active: false,
    password: 'user33123',
  },
  {
    id: 34,
    name: 'User34',
    email: 'user34@example.com',
    role: 'user',
    active: true,
    password: 'user34123',
  },
  {
    id: 35,
    name: 'User35',
    email: 'user35@example.com',
    role: 'user',
    active: false,
    password: 'user35123',
  },
  {
    id: 36,
    name: 'User36',
    email: 'user36@example.com',
    role: 'user',
    active: true,
    password: 'user36123',
  },
  {
    id: 37,
    name: 'User37',
    email: 'user37@example.com',
    role: 'user',
    active: false,
    password: 'user37123',
  },
  {
    id: 38,
    name: 'User38',
    email: 'user38@example.com',
    role: 'user',
    active: true,
    password: 'user38123',
  },
  {
    id: 39,
    name: 'User39',
    email: 'user39@example.com',
    role: 'user',
    active: false,
    password: 'user39123',
  },
  {
    id: 40,
    name: 'User40',
    email: 'user40@example.com',
    role: 'user',
    active: true,
    password: 'user40123',
  },
  {
    id: 41,
    name: 'User41',
    email: 'user41@example.com',
    role: 'user',
    active: false,
    password: 'user41123',
  },
  {
    id: 42,
    name: 'User42',
    email: 'user42@example.com',
    role: 'user',
    active: true,
    password: 'user42123',
  },
  {
    id: 43,
    name: 'User43',
    email: 'user43@example.com',
    role: 'user',
    active: false,
    password: 'user43123',
  },
  {
    id: 44,
    name: 'User44',
    email: 'user44@example.com',
    role: 'user',
    active: true,
    password: 'user44123',
  },
  {
    id: 45,
    name: 'User45',
    email: 'user45@example.com',
    role: 'user',
    active: false,
    password: 'user45123',
  },
  {
    id: 46,
    name: 'User46',
    email: 'user46@example.com',
    role: 'user',
    active: true,
    password: 'user46123',
  },
  {
    id: 47,
    name: 'User47',
    email: 'user47@example.com',
    role: 'user',
    active: false,
    password: 'user47123',
  },
  {
    id: 48,
    name: 'User48',
    email: 'user48@example.com',
    role: 'user',
    active: true,
    password: 'user48123',
  },
  {
    id: 49,
    name: 'User49',
    email: 'user49@example.com',
    role: 'user',
    active: false,
    password: 'user49123',
  },
  {
    id: 50,
    name: 'User50',
    email: 'user50@example.com',
    role: 'user',
    active: true,
    password: 'user50123',
  },
]
